//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/sceneControllerScript/gameMechanics/input_configuration/PlayerInputAction.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInputAction : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInputAction()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInputAction"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""183332d7-dbb6-4782-8743-114209d597af"",
            ""actions"": [
                {
                    ""name"": ""Run"",
                    ""type"": ""Button"",
                    ""id"": ""0063a5bd-fa30-4334-bb18-21ea86bfd5cd"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DiscardAction"",
                    ""type"": ""Button"",
                    ""id"": ""75d1322b-0a14-4d98-a5a5-6a8d722049ba"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""AnalogMovement"",
                    ""type"": ""PassThrough"",
                    ""id"": ""4a37ee72-ad4a-49b5-ad30-e8d0ca7f7cb2"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""AnalogRotation"",
                    ""type"": ""PassThrough"",
                    ""id"": ""3820c136-5067-4b97-9e65-b337b7ecf912"",
                    ""expectedControlType"": ""Stick"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""InventoryNextWeapon"",
                    ""type"": ""Button"",
                    ""id"": ""3acacdaa-7154-4605-a87d-d488fc921e75"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""InventoryPreviousWeapon"",
                    ""type"": ""Button"",
                    ""id"": ""8ea119c8-2d7e-4e86-aafb-906319194511"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""InventoryUseWeaponItem"",
                    ""type"": ""Button"",
                    ""id"": ""0cfc43b8-a725-4d5f-906f-d9e7032fb676"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PutAwayWeapon"",
                    ""type"": ""Button"",
                    ""id"": ""293a1bf6-3879-4892-8ac4-5320e0ea32c9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ExtractWeapon"",
                    ""type"": ""Button"",
                    ""id"": ""6d5b8fb8-233e-4d44-9b34-adae2e66c644"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Pause"",
                    ""type"": ""Button"",
                    ""id"": ""bcea35d9-ab76-416e-bdaf-ff61a86cb241"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SwitchCharacterMode"",
                    ""type"": ""Button"",
                    ""id"": ""4b24af32-458d-4c3d-b094-786e229cfef4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""a45388a0-0dcc-4b02-a0ea-218c33445c2e"",
                    ""path"": ""<XInputController>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Xbox Control Scheme"",
                    ""action"": ""Run"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""67be78c2-e33f-4a39-bb8e-1b337b94f39c"",
                    ""path"": ""<DualShockGamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Xbox Control Scheme"",
                    ""action"": ""Run"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""32d4ced5-f819-4979-a5d7-e710991cbb5c"",
                    ""path"": ""2DVector(mode=2)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AnalogMovement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""dd62e76b-eed5-4771-83c5-46a640e4a564"",
                    ""path"": ""<XInputController>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Xbox Control Scheme"",
                    ""action"": ""AnalogMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""c3838c12-7738-4527-a161-40676921ecbe"",
                    ""path"": ""<XInputController>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Xbox Control Scheme"",
                    ""action"": ""AnalogMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""75049201-0454-4ae3-a3c1-14558bc9314b"",
                    ""path"": ""<XInputController>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Xbox Control Scheme"",
                    ""action"": ""AnalogMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""19326fc8-49bd-4f4e-8f13-fcb670d618ea"",
                    ""path"": ""<XInputController>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Xbox Control Scheme"",
                    ""action"": ""AnalogMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""52f8b190-adc6-4fae-bc4c-c1a693a2d670"",
                    ""path"": ""2DVector(mode=2)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AnalogMovement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""4362e178-f8e2-427f-8777-5501d971ac46"",
                    ""path"": ""<DualShockGamepad>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Xbox Control Scheme"",
                    ""action"": ""AnalogMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""651a4b5e-f887-42c1-aa26-471862f672b6"",
                    ""path"": ""<DualShockGamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Xbox Control Scheme"",
                    ""action"": ""AnalogMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""68d640ef-d431-4baf-92b5-a20beecff964"",
                    ""path"": ""<DualShockGamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Xbox Control Scheme"",
                    ""action"": ""AnalogMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""fd45a983-c0c3-407e-ad7f-33a74dca06d5"",
                    ""path"": ""<DualShockGamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Xbox Control Scheme"",
                    ""action"": ""AnalogMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""4bce17dc-2fb4-4a71-821e-2b2f9f5d62cf"",
                    ""path"": ""2DVector(mode=2)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Xbox Control Scheme"",
                    ""action"": ""AnalogRotation"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""right"",
                    ""id"": ""32175300-65ef-43dd-afcc-06da0045a586"",
                    ""path"": ""<XInputController>/rightStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Xbox Control Scheme"",
                    ""action"": ""AnalogRotation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""f2625b89-48fa-4263-beee-3cb011099c4f"",
                    ""path"": ""<XInputController>/rightStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Xbox Control Scheme"",
                    ""action"": ""AnalogRotation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""5df52a33-0573-45c6-ba2b-c8dd9e6c677a"",
                    ""path"": ""<XInputController>/rightStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Xbox Control Scheme"",
                    ""action"": ""AnalogRotation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""up"",
                    ""id"": ""c6101fc7-d41d-4c8f-a04b-0c848635ecaa"",
                    ""path"": ""<XInputController>/rightStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Xbox Control Scheme"",
                    ""action"": ""AnalogRotation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""237a1688-82f4-45ba-b031-4963bd364f6e"",
                    ""path"": ""2DVector(mode=2)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Xbox Control Scheme"",
                    ""action"": ""AnalogRotation"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""right"",
                    ""id"": ""5f227ca1-2936-4b80-85f9-90f4d4f39c5c"",
                    ""path"": ""<DualShockGamepad>/rightStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Xbox Control Scheme"",
                    ""action"": ""AnalogRotation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""b31217f5-f3a9-4211-93c2-6f3489e0777d"",
                    ""path"": ""<DualShockGamepad>/rightStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Xbox Control Scheme"",
                    ""action"": ""AnalogRotation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""ed57359b-065b-4cfa-aea4-601d174e4dcf"",
                    ""path"": ""<DualShockGamepad>/rightStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Xbox Control Scheme"",
                    ""action"": ""AnalogRotation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""up"",
                    ""id"": ""7a412ffc-afcd-41f9-bd6b-b272819360ad"",
                    ""path"": ""<DualShockGamepad>/rightStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Xbox Control Scheme"",
                    ""action"": ""AnalogRotation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""5d1d137d-6c35-43c1-ae63-765b09bcc6cd"",
                    ""path"": ""<XInputController>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Xbox Control Scheme"",
                    ""action"": ""InventoryNextWeapon"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1e2fa66a-20ed-405d-b6e5-61415ab93a92"",
                    ""path"": ""<DualShockGamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Xbox Control Scheme"",
                    ""action"": ""InventoryNextWeapon"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3f62d7a8-60d3-4dc4-a87f-64158c0fdac4"",
                    ""path"": ""<XInputController>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Xbox Control Scheme"",
                    ""action"": ""InventoryPreviousWeapon"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bbb193fb-0aa1-4083-b671-35d9b5918e55"",
                    ""path"": ""<DualShockGamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Xbox Control Scheme"",
                    ""action"": ""InventoryPreviousWeapon"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""61fa808a-f83b-4862-a38f-eb571fcef398"",
                    ""path"": ""<XInputController>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Xbox Control Scheme"",
                    ""action"": ""InventoryUseWeaponItem"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""717558b8-7118-4b84-9854-6db4ccca4690"",
                    ""path"": ""<DualShockGamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Xbox Control Scheme"",
                    ""action"": ""InventoryUseWeaponItem"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1dbb6f2f-65f7-4916-b0c9-c339edfccb86"",
                    ""path"": ""<XInputController>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Xbox Control Scheme"",
                    ""action"": ""PutAwayWeapon"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c38bb96a-297e-44ee-9d42-8707283d040a"",
                    ""path"": ""<DualShockGamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Xbox Control Scheme"",
                    ""action"": ""PutAwayWeapon"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a3e34308-c800-41b5-8301-0e726dd1e1eb"",
                    ""path"": ""<XInputController>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Xbox Control Scheme"",
                    ""action"": ""DiscardAction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""26651639-c1de-4bb9-ba6d-a6cb5f98cb84"",
                    ""path"": ""<DualShockGamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Xbox Control Scheme"",
                    ""action"": ""DiscardAction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""646d209e-29f9-4ca3-99fb-89c33f48cb26"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Xbox Control Scheme"",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""322e7601-39c8-4d1d-a276-45f22f3d9df7"",
                    ""path"": ""<DualShockGamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""064c88b6-4bfc-49b1-b91a-dc2e4f4e1a8c"",
                    ""path"": ""<XInputController>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Xbox Control Scheme"",
                    ""action"": ""ExtractWeapon"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""16a11f4e-a718-4e5b-83e0-5eda16c50ea0"",
                    ""path"": ""<DualShockGamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Xbox Control Scheme"",
                    ""action"": ""ExtractWeapon"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4f279345-533f-41a1-8d34-115e0e4b8ad0"",
                    ""path"": ""<Gamepad>/select"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Xbox Control Scheme"",
                    ""action"": ""SwitchCharacterMode"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""28314b0a-bdd5-4c20-bf21-ae563fd3acb0"",
                    ""path"": ""<DualShockGamepad>/select"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwitchCharacterMode"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""UI"",
            ""id"": ""46a38724-d632-48d9-a8c2-a42e2f21609a"",
            ""actions"": [
                {
                    ""name"": ""Action"",
                    ""type"": ""PassThrough"",
                    ""id"": ""1a54737e-0f00-46dc-a6a5-480909ad815c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MenuNavigation"",
                    ""type"": ""Value"",
                    ""id"": ""36351262-daa6-4744-8486-c6896bedb80d"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""3f02bb0f-9374-424b-a568-d783456e2591"",
                    ""path"": ""<XInputController>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Xbox Control Scheme"",
                    ""action"": ""Action"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fcbd7d83-b3a2-4a6b-8c27-7edf552171a8"",
                    ""path"": ""<DualShockGamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Xbox Control Scheme"",
                    ""action"": ""Action"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""de39514a-3124-489c-a719-e117df35cf92"",
                    ""path"": ""<XInputController>/dpad"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Xbox Control Scheme"",
                    ""action"": ""MenuNavigation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""51837914-07a8-4dfa-931d-d36d416afc60"",
                    ""path"": ""<DualShockGamepad>/dpad"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Xbox Control Scheme"",
                    ""action"": ""MenuNavigation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""MainMenu"",
            ""id"": ""811c0a19-ebe4-4fa3-acaa-6c98c6e3b8f7"",
            ""actions"": [
                {
                    ""name"": ""MenuNavigation"",
                    ""type"": ""Value"",
                    ""id"": ""869ade71-2a37-441b-9042-6fce8b9af9b5"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Action"",
                    ""type"": ""Button"",
                    ""id"": ""ed97980e-1d2b-4630-8921-8543bb2f8525"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ButtonBack"",
                    ""type"": ""Button"",
                    ""id"": ""a80efcd5-9311-4dcc-b8f0-47eb7b239214"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MenuScroll"",
                    ""type"": ""PassThrough"",
                    ""id"": ""3b1c77e1-a01a-44bc-9559-31cad529fd50"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""7f4065d7-f232-4135-b576-8f771fa8c788"",
                    ""path"": ""<DualShockGamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Xbox Control Scheme"",
                    ""action"": ""Action"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""905adb37-a67e-4031-b378-b1cf50b3bb5c"",
                    ""path"": ""<XInputController>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Xbox Control Scheme"",
                    ""action"": ""Action"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c9b8d813-57d5-485c-aaa9-47cb774562f8"",
                    ""path"": ""<XInputController>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Xbox Control Scheme"",
                    ""action"": ""ButtonBack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""adc4839f-7002-45fc-a07b-e84ee583b5dc"",
                    ""path"": ""<DualShockGamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Xbox Control Scheme"",
                    ""action"": ""ButtonBack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector Playstation stick"",
                    ""id"": ""d0ff928d-c0dd-40fe-9bcb-d52c94c14d5d"",
                    ""path"": ""2DVector(mode=2)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MenuScroll"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""f5500a63-a907-4816-a91f-2579f01b3626"",
                    ""path"": ""<DualShockGamepad>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Xbox Control Scheme"",
                    ""action"": ""MenuScroll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""be2773f0-6fce-43d3-823b-d84e04d6ad32"",
                    ""path"": ""<DualShockGamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Xbox Control Scheme"",
                    ""action"": ""MenuScroll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""2D Vector Playstation dpad"",
                    ""id"": ""eaaf4983-4b9c-46aa-b499-b45c930aba80"",
                    ""path"": ""2DVector(mode=2)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MenuScroll"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""76ea3d75-7872-4ab4-ae2c-6609be05c681"",
                    ""path"": ""<DualShockGamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Xbox Control Scheme"",
                    ""action"": ""MenuScroll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""55d6d066-f2db-4fb2-a94f-01969d352f19"",
                    ""path"": ""<DualShockGamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Xbox Control Scheme"",
                    ""action"": ""MenuScroll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""2D Vector Xbox stick"",
                    ""id"": ""deba57e9-31f2-4d13-ac4a-d2bc60c75174"",
                    ""path"": ""2DVector(mode=2)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MenuScroll"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""2519ae8b-64d2-43a6-af3d-9c248c56ff9d"",
                    ""path"": ""<XInputController>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Xbox Control Scheme"",
                    ""action"": ""MenuScroll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""38f40b05-b638-48b0-97d5-45615e60148f"",
                    ""path"": ""<XInputController>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Xbox Control Scheme"",
                    ""action"": ""MenuScroll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""2D Vector Xbox dpad"",
                    ""id"": ""725fd5da-6774-4b83-bbda-5c67df017fcb"",
                    ""path"": ""2DVector(mode=2)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MenuScroll"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""831d4256-16ca-4430-868d-eb19f97466f5"",
                    ""path"": ""<XInputController>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Xbox Control Scheme"",
                    ""action"": ""MenuScroll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""9ef05434-1ab0-40aa-a8b1-c2a0267ff303"",
                    ""path"": ""<XInputController>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Xbox Control Scheme"",
                    ""action"": ""MenuScroll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""2D Vector Playstation stick"",
                    ""id"": ""af19eb10-7c70-4466-be46-0711f28e3d38"",
                    ""path"": ""2DVector(mode=2)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MenuNavigation"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""right"",
                    ""id"": ""67da215d-7e52-4895-8741-42fc048d3075"",
                    ""path"": ""<XInputController>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Xbox Control Scheme"",
                    ""action"": ""MenuNavigation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""dd21f932-598d-45b2-ae2f-b4acd99f8bf4"",
                    ""path"": ""<XInputController>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Xbox Control Scheme"",
                    ""action"": ""MenuNavigation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""2D Vector Xbox stick"",
                    ""id"": ""d7448934-3518-4e89-8949-3fed9f22f19d"",
                    ""path"": ""2DVector(mode=2)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MenuNavigation"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""right"",
                    ""id"": ""7c69fb26-552d-4152-81a8-addc301eeee9"",
                    ""path"": ""<DualShockGamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Xbox Control Scheme"",
                    ""action"": ""MenuNavigation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""534a3d0e-24dc-4ab1-b2cb-775e9ef8e9a1"",
                    ""path"": ""<DualShockGamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Xbox Control Scheme"",
                    ""action"": ""MenuNavigation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        },
        {
            ""name"": ""SwitchCharacterMode"",
            ""id"": ""80b7c048-6623-4062-95e2-1ad0a2b802d1"",
            ""actions"": [
                {
                    ""name"": ""PreviousCharacter"",
                    ""type"": ""Button"",
                    ""id"": ""7008f4f3-9496-4553-8b52-d590d301b121"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""NextCharacter"",
                    ""type"": ""Button"",
                    ""id"": ""cc81f663-1103-4e80-bd2d-408f572458e2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DiscardAction"",
                    ""type"": ""Button"",
                    ""id"": ""185e47d9-ad02-4906-a8a4-0c7fb8a2004c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Action"",
                    ""type"": ""PassThrough"",
                    ""id"": ""3e805766-ea23-4117-96ac-488c63d46a37"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""8e207514-6bc5-4a13-a896-52cf08047bce"",
                    ""path"": ""<XInputController>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Xbox Control Scheme"",
                    ""action"": ""PreviousCharacter"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7c40e39d-c578-4ced-b8ab-a0b20944c1b5"",
                    ""path"": ""<DualShockGamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Xbox Control Scheme"",
                    ""action"": ""PreviousCharacter"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""746b958a-2412-4b1c-95d3-da8df57af9ea"",
                    ""path"": ""<XInputController>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Xbox Control Scheme"",
                    ""action"": ""NextCharacter"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ed743ee2-b6cc-4f76-b906-087ceaf584e8"",
                    ""path"": ""<DualShockGamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Xbox Control Scheme"",
                    ""action"": ""NextCharacter"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2bc8acd0-4d6d-4bd0-98c4-716ee1ecab48"",
                    ""path"": ""<XInputController>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Xbox Control Scheme"",
                    ""action"": ""Action"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bdde9fb2-cb2f-4d60-aaa0-fadc94a20b59"",
                    ""path"": ""<DualShockGamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Xbox Control Scheme"",
                    ""action"": ""Action"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""86822ffe-e5b9-4750-9337-0843e8d01c5d"",
                    ""path"": ""<XInputController>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Xbox Control Scheme"",
                    ""action"": ""DiscardAction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a24c056c-4a44-434d-bfe4-0b1b3df56c8c"",
                    ""path"": ""<DualShockGamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Xbox Control Scheme"",
                    ""action"": ""DiscardAction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Xbox Control Scheme"",
            ""bindingGroup"": ""Xbox Control Scheme"",
            ""devices"": [
                {
                    ""devicePath"": ""<XInputController>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // Player
        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
        m_Player_Run = m_Player.FindAction("Run", throwIfNotFound: true);
        m_Player_DiscardAction = m_Player.FindAction("DiscardAction", throwIfNotFound: true);
        m_Player_AnalogMovement = m_Player.FindAction("AnalogMovement", throwIfNotFound: true);
        m_Player_AnalogRotation = m_Player.FindAction("AnalogRotation", throwIfNotFound: true);
        m_Player_InventoryNextWeapon = m_Player.FindAction("InventoryNextWeapon", throwIfNotFound: true);
        m_Player_InventoryPreviousWeapon = m_Player.FindAction("InventoryPreviousWeapon", throwIfNotFound: true);
        m_Player_InventoryUseWeaponItem = m_Player.FindAction("InventoryUseWeaponItem", throwIfNotFound: true);
        m_Player_PutAwayWeapon = m_Player.FindAction("PutAwayWeapon", throwIfNotFound: true);
        m_Player_ExtractWeapon = m_Player.FindAction("ExtractWeapon", throwIfNotFound: true);
        m_Player_Pause = m_Player.FindAction("Pause", throwIfNotFound: true);
        m_Player_SwitchCharacterMode = m_Player.FindAction("SwitchCharacterMode", throwIfNotFound: true);
        // UI
        m_UI = asset.FindActionMap("UI", throwIfNotFound: true);
        m_UI_Action = m_UI.FindAction("Action", throwIfNotFound: true);
        m_UI_MenuNavigation = m_UI.FindAction("MenuNavigation", throwIfNotFound: true);
        // MainMenu
        m_MainMenu = asset.FindActionMap("MainMenu", throwIfNotFound: true);
        m_MainMenu_MenuNavigation = m_MainMenu.FindAction("MenuNavigation", throwIfNotFound: true);
        m_MainMenu_Action = m_MainMenu.FindAction("Action", throwIfNotFound: true);
        m_MainMenu_ButtonBack = m_MainMenu.FindAction("ButtonBack", throwIfNotFound: true);
        m_MainMenu_MenuScroll = m_MainMenu.FindAction("MenuScroll", throwIfNotFound: true);
        // SwitchCharacterMode
        m_SwitchCharacterMode = asset.FindActionMap("SwitchCharacterMode", throwIfNotFound: true);
        m_SwitchCharacterMode_PreviousCharacter = m_SwitchCharacterMode.FindAction("PreviousCharacter", throwIfNotFound: true);
        m_SwitchCharacterMode_NextCharacter = m_SwitchCharacterMode.FindAction("NextCharacter", throwIfNotFound: true);
        m_SwitchCharacterMode_DiscardAction = m_SwitchCharacterMode.FindAction("DiscardAction", throwIfNotFound: true);
        m_SwitchCharacterMode_Action = m_SwitchCharacterMode.FindAction("Action", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player
    private readonly InputActionMap m_Player;
    private IPlayerActions m_PlayerActionsCallbackInterface;
    private readonly InputAction m_Player_Run;
    private readonly InputAction m_Player_DiscardAction;
    private readonly InputAction m_Player_AnalogMovement;
    private readonly InputAction m_Player_AnalogRotation;
    private readonly InputAction m_Player_InventoryNextWeapon;
    private readonly InputAction m_Player_InventoryPreviousWeapon;
    private readonly InputAction m_Player_InventoryUseWeaponItem;
    private readonly InputAction m_Player_PutAwayWeapon;
    private readonly InputAction m_Player_ExtractWeapon;
    private readonly InputAction m_Player_Pause;
    private readonly InputAction m_Player_SwitchCharacterMode;
    public struct PlayerActions
    {
        private @PlayerInputAction m_Wrapper;
        public PlayerActions(@PlayerInputAction wrapper) { m_Wrapper = wrapper; }
        public InputAction @Run => m_Wrapper.m_Player_Run;
        public InputAction @DiscardAction => m_Wrapper.m_Player_DiscardAction;
        public InputAction @AnalogMovement => m_Wrapper.m_Player_AnalogMovement;
        public InputAction @AnalogRotation => m_Wrapper.m_Player_AnalogRotation;
        public InputAction @InventoryNextWeapon => m_Wrapper.m_Player_InventoryNextWeapon;
        public InputAction @InventoryPreviousWeapon => m_Wrapper.m_Player_InventoryPreviousWeapon;
        public InputAction @InventoryUseWeaponItem => m_Wrapper.m_Player_InventoryUseWeaponItem;
        public InputAction @PutAwayWeapon => m_Wrapper.m_Player_PutAwayWeapon;
        public InputAction @ExtractWeapon => m_Wrapper.m_Player_ExtractWeapon;
        public InputAction @Pause => m_Wrapper.m_Player_Pause;
        public InputAction @SwitchCharacterMode => m_Wrapper.m_Player_SwitchCharacterMode;
        public InputActionMap Get() { return m_Wrapper.m_Player; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        public void SetCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterface != null)
            {
                @Run.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnRun;
                @Run.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnRun;
                @Run.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnRun;
                @DiscardAction.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnDiscardAction;
                @DiscardAction.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnDiscardAction;
                @DiscardAction.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnDiscardAction;
                @AnalogMovement.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnAnalogMovement;
                @AnalogMovement.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnAnalogMovement;
                @AnalogMovement.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnAnalogMovement;
                @AnalogRotation.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnAnalogRotation;
                @AnalogRotation.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnAnalogRotation;
                @AnalogRotation.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnAnalogRotation;
                @InventoryNextWeapon.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnInventoryNextWeapon;
                @InventoryNextWeapon.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnInventoryNextWeapon;
                @InventoryNextWeapon.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnInventoryNextWeapon;
                @InventoryPreviousWeapon.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnInventoryPreviousWeapon;
                @InventoryPreviousWeapon.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnInventoryPreviousWeapon;
                @InventoryPreviousWeapon.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnInventoryPreviousWeapon;
                @InventoryUseWeaponItem.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnInventoryUseWeaponItem;
                @InventoryUseWeaponItem.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnInventoryUseWeaponItem;
                @InventoryUseWeaponItem.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnInventoryUseWeaponItem;
                @PutAwayWeapon.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnPutAwayWeapon;
                @PutAwayWeapon.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnPutAwayWeapon;
                @PutAwayWeapon.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnPutAwayWeapon;
                @ExtractWeapon.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnExtractWeapon;
                @ExtractWeapon.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnExtractWeapon;
                @ExtractWeapon.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnExtractWeapon;
                @Pause.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnPause;
                @Pause.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnPause;
                @Pause.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnPause;
                @SwitchCharacterMode.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSwitchCharacterMode;
                @SwitchCharacterMode.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSwitchCharacterMode;
                @SwitchCharacterMode.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSwitchCharacterMode;
            }
            m_Wrapper.m_PlayerActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Run.started += instance.OnRun;
                @Run.performed += instance.OnRun;
                @Run.canceled += instance.OnRun;
                @DiscardAction.started += instance.OnDiscardAction;
                @DiscardAction.performed += instance.OnDiscardAction;
                @DiscardAction.canceled += instance.OnDiscardAction;
                @AnalogMovement.started += instance.OnAnalogMovement;
                @AnalogMovement.performed += instance.OnAnalogMovement;
                @AnalogMovement.canceled += instance.OnAnalogMovement;
                @AnalogRotation.started += instance.OnAnalogRotation;
                @AnalogRotation.performed += instance.OnAnalogRotation;
                @AnalogRotation.canceled += instance.OnAnalogRotation;
                @InventoryNextWeapon.started += instance.OnInventoryNextWeapon;
                @InventoryNextWeapon.performed += instance.OnInventoryNextWeapon;
                @InventoryNextWeapon.canceled += instance.OnInventoryNextWeapon;
                @InventoryPreviousWeapon.started += instance.OnInventoryPreviousWeapon;
                @InventoryPreviousWeapon.performed += instance.OnInventoryPreviousWeapon;
                @InventoryPreviousWeapon.canceled += instance.OnInventoryPreviousWeapon;
                @InventoryUseWeaponItem.started += instance.OnInventoryUseWeaponItem;
                @InventoryUseWeaponItem.performed += instance.OnInventoryUseWeaponItem;
                @InventoryUseWeaponItem.canceled += instance.OnInventoryUseWeaponItem;
                @PutAwayWeapon.started += instance.OnPutAwayWeapon;
                @PutAwayWeapon.performed += instance.OnPutAwayWeapon;
                @PutAwayWeapon.canceled += instance.OnPutAwayWeapon;
                @ExtractWeapon.started += instance.OnExtractWeapon;
                @ExtractWeapon.performed += instance.OnExtractWeapon;
                @ExtractWeapon.canceled += instance.OnExtractWeapon;
                @Pause.started += instance.OnPause;
                @Pause.performed += instance.OnPause;
                @Pause.canceled += instance.OnPause;
                @SwitchCharacterMode.started += instance.OnSwitchCharacterMode;
                @SwitchCharacterMode.performed += instance.OnSwitchCharacterMode;
                @SwitchCharacterMode.canceled += instance.OnSwitchCharacterMode;
            }
        }
    }
    public PlayerActions @Player => new PlayerActions(this);

    // UI
    private readonly InputActionMap m_UI;
    private IUIActions m_UIActionsCallbackInterface;
    private readonly InputAction m_UI_Action;
    private readonly InputAction m_UI_MenuNavigation;
    public struct UIActions
    {
        private @PlayerInputAction m_Wrapper;
        public UIActions(@PlayerInputAction wrapper) { m_Wrapper = wrapper; }
        public InputAction @Action => m_Wrapper.m_UI_Action;
        public InputAction @MenuNavigation => m_Wrapper.m_UI_MenuNavigation;
        public InputActionMap Get() { return m_Wrapper.m_UI; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(UIActions set) { return set.Get(); }
        public void SetCallbacks(IUIActions instance)
        {
            if (m_Wrapper.m_UIActionsCallbackInterface != null)
            {
                @Action.started -= m_Wrapper.m_UIActionsCallbackInterface.OnAction;
                @Action.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnAction;
                @Action.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnAction;
                @MenuNavigation.started -= m_Wrapper.m_UIActionsCallbackInterface.OnMenuNavigation;
                @MenuNavigation.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnMenuNavigation;
                @MenuNavigation.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnMenuNavigation;
            }
            m_Wrapper.m_UIActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Action.started += instance.OnAction;
                @Action.performed += instance.OnAction;
                @Action.canceled += instance.OnAction;
                @MenuNavigation.started += instance.OnMenuNavigation;
                @MenuNavigation.performed += instance.OnMenuNavigation;
                @MenuNavigation.canceled += instance.OnMenuNavigation;
            }
        }
    }
    public UIActions @UI => new UIActions(this);

    // MainMenu
    private readonly InputActionMap m_MainMenu;
    private IMainMenuActions m_MainMenuActionsCallbackInterface;
    private readonly InputAction m_MainMenu_MenuNavigation;
    private readonly InputAction m_MainMenu_Action;
    private readonly InputAction m_MainMenu_ButtonBack;
    private readonly InputAction m_MainMenu_MenuScroll;
    public struct MainMenuActions
    {
        private @PlayerInputAction m_Wrapper;
        public MainMenuActions(@PlayerInputAction wrapper) { m_Wrapper = wrapper; }
        public InputAction @MenuNavigation => m_Wrapper.m_MainMenu_MenuNavigation;
        public InputAction @Action => m_Wrapper.m_MainMenu_Action;
        public InputAction @ButtonBack => m_Wrapper.m_MainMenu_ButtonBack;
        public InputAction @MenuScroll => m_Wrapper.m_MainMenu_MenuScroll;
        public InputActionMap Get() { return m_Wrapper.m_MainMenu; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MainMenuActions set) { return set.Get(); }
        public void SetCallbacks(IMainMenuActions instance)
        {
            if (m_Wrapper.m_MainMenuActionsCallbackInterface != null)
            {
                @MenuNavigation.started -= m_Wrapper.m_MainMenuActionsCallbackInterface.OnMenuNavigation;
                @MenuNavigation.performed -= m_Wrapper.m_MainMenuActionsCallbackInterface.OnMenuNavigation;
                @MenuNavigation.canceled -= m_Wrapper.m_MainMenuActionsCallbackInterface.OnMenuNavigation;
                @Action.started -= m_Wrapper.m_MainMenuActionsCallbackInterface.OnAction;
                @Action.performed -= m_Wrapper.m_MainMenuActionsCallbackInterface.OnAction;
                @Action.canceled -= m_Wrapper.m_MainMenuActionsCallbackInterface.OnAction;
                @ButtonBack.started -= m_Wrapper.m_MainMenuActionsCallbackInterface.OnButtonBack;
                @ButtonBack.performed -= m_Wrapper.m_MainMenuActionsCallbackInterface.OnButtonBack;
                @ButtonBack.canceled -= m_Wrapper.m_MainMenuActionsCallbackInterface.OnButtonBack;
                @MenuScroll.started -= m_Wrapper.m_MainMenuActionsCallbackInterface.OnMenuScroll;
                @MenuScroll.performed -= m_Wrapper.m_MainMenuActionsCallbackInterface.OnMenuScroll;
                @MenuScroll.canceled -= m_Wrapper.m_MainMenuActionsCallbackInterface.OnMenuScroll;
            }
            m_Wrapper.m_MainMenuActionsCallbackInterface = instance;
            if (instance != null)
            {
                @MenuNavigation.started += instance.OnMenuNavigation;
                @MenuNavigation.performed += instance.OnMenuNavigation;
                @MenuNavigation.canceled += instance.OnMenuNavigation;
                @Action.started += instance.OnAction;
                @Action.performed += instance.OnAction;
                @Action.canceled += instance.OnAction;
                @ButtonBack.started += instance.OnButtonBack;
                @ButtonBack.performed += instance.OnButtonBack;
                @ButtonBack.canceled += instance.OnButtonBack;
                @MenuScroll.started += instance.OnMenuScroll;
                @MenuScroll.performed += instance.OnMenuScroll;
                @MenuScroll.canceled += instance.OnMenuScroll;
            }
        }
    }
    public MainMenuActions @MainMenu => new MainMenuActions(this);

    // SwitchCharacterMode
    private readonly InputActionMap m_SwitchCharacterMode;
    private ISwitchCharacterModeActions m_SwitchCharacterModeActionsCallbackInterface;
    private readonly InputAction m_SwitchCharacterMode_PreviousCharacter;
    private readonly InputAction m_SwitchCharacterMode_NextCharacter;
    private readonly InputAction m_SwitchCharacterMode_DiscardAction;
    private readonly InputAction m_SwitchCharacterMode_Action;
    public struct SwitchCharacterModeActions
    {
        private @PlayerInputAction m_Wrapper;
        public SwitchCharacterModeActions(@PlayerInputAction wrapper) { m_Wrapper = wrapper; }
        public InputAction @PreviousCharacter => m_Wrapper.m_SwitchCharacterMode_PreviousCharacter;
        public InputAction @NextCharacter => m_Wrapper.m_SwitchCharacterMode_NextCharacter;
        public InputAction @DiscardAction => m_Wrapper.m_SwitchCharacterMode_DiscardAction;
        public InputAction @Action => m_Wrapper.m_SwitchCharacterMode_Action;
        public InputActionMap Get() { return m_Wrapper.m_SwitchCharacterMode; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(SwitchCharacterModeActions set) { return set.Get(); }
        public void SetCallbacks(ISwitchCharacterModeActions instance)
        {
            if (m_Wrapper.m_SwitchCharacterModeActionsCallbackInterface != null)
            {
                @PreviousCharacter.started -= m_Wrapper.m_SwitchCharacterModeActionsCallbackInterface.OnPreviousCharacter;
                @PreviousCharacter.performed -= m_Wrapper.m_SwitchCharacterModeActionsCallbackInterface.OnPreviousCharacter;
                @PreviousCharacter.canceled -= m_Wrapper.m_SwitchCharacterModeActionsCallbackInterface.OnPreviousCharacter;
                @NextCharacter.started -= m_Wrapper.m_SwitchCharacterModeActionsCallbackInterface.OnNextCharacter;
                @NextCharacter.performed -= m_Wrapper.m_SwitchCharacterModeActionsCallbackInterface.OnNextCharacter;
                @NextCharacter.canceled -= m_Wrapper.m_SwitchCharacterModeActionsCallbackInterface.OnNextCharacter;
                @DiscardAction.started -= m_Wrapper.m_SwitchCharacterModeActionsCallbackInterface.OnDiscardAction;
                @DiscardAction.performed -= m_Wrapper.m_SwitchCharacterModeActionsCallbackInterface.OnDiscardAction;
                @DiscardAction.canceled -= m_Wrapper.m_SwitchCharacterModeActionsCallbackInterface.OnDiscardAction;
                @Action.started -= m_Wrapper.m_SwitchCharacterModeActionsCallbackInterface.OnAction;
                @Action.performed -= m_Wrapper.m_SwitchCharacterModeActionsCallbackInterface.OnAction;
                @Action.canceled -= m_Wrapper.m_SwitchCharacterModeActionsCallbackInterface.OnAction;
            }
            m_Wrapper.m_SwitchCharacterModeActionsCallbackInterface = instance;
            if (instance != null)
            {
                @PreviousCharacter.started += instance.OnPreviousCharacter;
                @PreviousCharacter.performed += instance.OnPreviousCharacter;
                @PreviousCharacter.canceled += instance.OnPreviousCharacter;
                @NextCharacter.started += instance.OnNextCharacter;
                @NextCharacter.performed += instance.OnNextCharacter;
                @NextCharacter.canceled += instance.OnNextCharacter;
                @DiscardAction.started += instance.OnDiscardAction;
                @DiscardAction.performed += instance.OnDiscardAction;
                @DiscardAction.canceled += instance.OnDiscardAction;
                @Action.started += instance.OnAction;
                @Action.performed += instance.OnAction;
                @Action.canceled += instance.OnAction;
            }
        }
    }
    public SwitchCharacterModeActions @SwitchCharacterMode => new SwitchCharacterModeActions(this);
    private int m_XboxControlSchemeSchemeIndex = -1;
    public InputControlScheme XboxControlSchemeScheme
    {
        get
        {
            if (m_XboxControlSchemeSchemeIndex == -1) m_XboxControlSchemeSchemeIndex = asset.FindControlSchemeIndex("Xbox Control Scheme");
            return asset.controlSchemes[m_XboxControlSchemeSchemeIndex];
        }
    }
    public interface IPlayerActions
    {
        void OnRun(InputAction.CallbackContext context);
        void OnDiscardAction(InputAction.CallbackContext context);
        void OnAnalogMovement(InputAction.CallbackContext context);
        void OnAnalogRotation(InputAction.CallbackContext context);
        void OnInventoryNextWeapon(InputAction.CallbackContext context);
        void OnInventoryPreviousWeapon(InputAction.CallbackContext context);
        void OnInventoryUseWeaponItem(InputAction.CallbackContext context);
        void OnPutAwayWeapon(InputAction.CallbackContext context);
        void OnExtractWeapon(InputAction.CallbackContext context);
        void OnPause(InputAction.CallbackContext context);
        void OnSwitchCharacterMode(InputAction.CallbackContext context);
    }
    public interface IUIActions
    {
        void OnAction(InputAction.CallbackContext context);
        void OnMenuNavigation(InputAction.CallbackContext context);
    }
    public interface IMainMenuActions
    {
        void OnMenuNavigation(InputAction.CallbackContext context);
        void OnAction(InputAction.CallbackContext context);
        void OnButtonBack(InputAction.CallbackContext context);
        void OnMenuScroll(InputAction.CallbackContext context);
    }
    public interface ISwitchCharacterModeActions
    {
        void OnPreviousCharacter(InputAction.CallbackContext context);
        void OnNextCharacter(InputAction.CallbackContext context);
        void OnDiscardAction(InputAction.CallbackContext context);
        void OnAction(InputAction.CallbackContext context);
    }
}
